COL_IP_SRC = 0
COL_IP_DST = 2
COL_PORT_DST = 3
COL_START_TIME = 4
COL_NUMERO_PAQUETES_SRC_DST = 16
COL_NUMERO_PAQUETES_DST_SRC = 17

UMBRAL_PESO_VERTICAL = 15
UMBRAL_HOSTS_HORIZONTAL = 3
PUERTOS_CONOCIDOS = [22, 23, 25, 3389]
PESO_PUERTOS_CONOCIDOS = 5
PESO_PUERTOS_COMUNES = 3
UMBRAL_PESO_MIXTO = 6
MIN_HOSTS_MIXTO = 2