from .manejar_variables_entrada import parseArgs
from .imprimir import imprimir_resultado, imprimir_resultado_json, imprimirEstadisticas, acumular_estadisticas_dia, imprimir_estadisticas_por_dia
from .leer_archivos import localizar_archivos_flujos, leer_registros_flujo_ordenados
from .redes import esIpInterna
